ExUnit.start()
Mox.defmock(PleromaRedux.Auth.Mock, for: PleromaRedux.Auth)
Mox.defmock(PleromaRedux.Discovery.Mock, for: PleromaRedux.Discovery)
Mox.defmock(PleromaRedux.HTTP.Mock, for: PleromaRedux.HTTP)
Mox.defmock(PleromaRedux.AvatarStorage.Mock, for: PleromaRedux.AvatarStorage)
Mox.defmock(PleromaRedux.MediaStorage.Mock, for: PleromaRedux.MediaStorage)
Ecto.Adapters.SQL.Sandbox.mode(PleromaRedux.Repo, :manual)
