ExUnit.start()
Mox.defmock(Egregoros.Auth.Mock, for: Egregoros.Auth)
Mox.defmock(Egregoros.Discovery.Mock, for: Egregoros.Discovery)
Mox.defmock(Egregoros.HTTP.Mock, for: Egregoros.HTTP)
Mox.defmock(Egregoros.DNS.Mock, for: Egregoros.DNS)
Mox.defmock(Egregoros.AuthZ.Mock, for: Egregoros.AuthZ)
Mox.defmock(Egregoros.AvatarStorage.Mock, for: Egregoros.AvatarStorage)
Mox.defmock(Egregoros.BannerStorage.Mock, for: Egregoros.BannerStorage)
Mox.defmock(Egregoros.MediaStorage.Mock, for: Egregoros.MediaStorage)
Ecto.Adapters.SQL.Sandbox.mode(Egregoros.Repo, :manual)
